"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 17:53:52.204197
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ghr.db

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "prereleases",
            sa.Enum("SHOW", "MUTE", "HIDE", name="prereleasemode", native_enum=False, length=8),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(length=2048), nullable=False),
        sa.Column("p256dh", sa.String(length=255), nullable=False),
        sa.Column("auth", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("owner_avatar_url", sa.String(length=1024), nullable=False),
        sa.Column("html_url", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("unsubscribed_at", ghr.db.UtcDateTime(), nullable=True),
        sa.Column("notifications_muted_at", ghr.db.UtcDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_repositories_full_name"), ["full_name"], unique=True)

    op.create_table(
        "summaries",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "sync_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_modified", sa.String(length=64), nullable=True),
        sa.Column("last_synced_at", ghr.db.UtcDateTime(), nullable=True),
        sa.Column("last_attempt_at", ghr.db.UtcDateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hide_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column("created_at", ghr.db.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "pattern"),
    )
    op.create_table(
        "readmes",
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("html_url", sa.String(length=1024), nullable=False),
        sa.Column("download_url", sa.String(length=1024), nullable=False),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("fetched_at", ghr.db.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("repository_id"),
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("tag_name", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("html_url", sa.String(length=1024), nullable=False),
        sa.Column("author_login", sa.String(length=255), nullable=True),
        sa.Column("author_avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("prerelease", sa.Boolean(), nullable=False),
        sa.Column("published_at", ghr.db.UtcDateTime(), nullable=False),
        sa.Column("read_at", ghr.db.UtcDateTime(), nullable=True),
        sa.Column("snoozed_until", ghr.db.UtcDateTime(), nullable=True),
        sa.Column("breaking", sa.Boolean(), nullable=False),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_releases_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_releases_read_at"), ["read_at"], unique=False)
        batch_op.create_index(
            "ix_releases_repository_published", ["repository_id", "published_at"], unique=False
        )
        batch_op.create_index(
            "ix_releases_repository_read", ["repository_id", "read_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_releases_snoozed_until"), ["snoozed_until"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_releases_snoozed_until"))
        batch_op.drop_index("ix_releases_repository_read")
        batch_op.drop_index("ix_releases_repository_published")
        batch_op.drop_index(batch_op.f("ix_releases_read_at"))
        batch_op.drop_index(batch_op.f("ix_releases_published_at"))

    op.drop_table("releases")
    op.drop_table("readmes")
    op.drop_table("hide_rules")
    op.drop_table("sync_state")
    op.drop_table("summaries")
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repositories_full_name"))

    op.drop_table("repositories")
    op.drop_table("push_subscriptions")
    op.drop_table("preferences")
    # ### end Alembic commands ###
