"""repository notification muting

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 14:13:29.435670
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ghr.db

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("notifications_muted_at", ghr.db.UtcDateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.drop_column("notifications_muted_at")

    # ### end Alembic commands ###
