"""snooze breaking preferences summaries

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 16:01:02.020406
"""

from collections.abc import Sequence
from itertools import groupby
from types import SimpleNamespace

import sqlalchemy as sa
from alembic import op

import ghr.db
from ghr.services import breaking

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_prereleases", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("notify_prereleases", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "summaries",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("created_at", ghr.db.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("snoozed_until", ghr.db.UtcDateTime(), nullable=True))
        batch_op.add_column(sa.Column("breaking", sa.Boolean(), server_default="0", nullable=False))
        batch_op.add_column(sa.Column("etag", sa.String(length=255), nullable=True))
        batch_op.create_index(
            "ix_releases_repository_published", ["repository_id", "published_at"], unique=False
        )
        batch_op.create_index(
            "ix_releases_repository_read", ["repository_id", "read_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_releases_snoozed_until"), ["snoozed_until"], unique=False
        )

    # ### end Alembic commands ###
    _classify_existing_releases()


def _classify_existing_releases() -> None:
    """Compute the new ``breaking`` flag for releases imported before it existed."""
    connection = op.get_bind()
    rows = connection.execute(
        sa.text(
            "SELECT id, repository_id, tag_name, body FROM releases "
            "ORDER BY repository_id, published_at, id"
        )
    ).all()
    releases = [
        SimpleNamespace(
            id=row.id,
            repository_id=row.repository_id,
            tag_name=row.tag_name,
            body=row.body,
            breaking=False,
        )
        for row in rows
    ]
    for _, group in groupby(releases, key=lambda release: release.repository_id):
        breaking.classify(list(group))
    flagged = [{"id": release.id} for release in releases if release.breaking]
    if flagged:
        connection.execute(sa.text("UPDATE releases SET breaking = 1 WHERE id = :id"), flagged)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_releases_snoozed_until"))
        batch_op.drop_index("ix_releases_repository_read")
        batch_op.drop_index("ix_releases_repository_published")
        batch_op.drop_column("etag")
        batch_op.drop_column("breaking")
        batch_op.drop_column("snoozed_until")

    op.drop_table("summaries")
    op.drop_table("preferences")
    # ### end Alembic commands ###
