import { AlertTriangleIcon, SparklesIcon } from "lucide-react"
import { lazy, Suspense } from "react"

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import type { MarkdownBaseUrls } from "@/lib/markdown-urls"

import { useSummarize, useSummaryConfig } from "./api"

const Markdown = lazy(() =>
  import("@/components/markdown").then((module) => ({ default: module.Markdown }))
)

interface SummaryPanelProps {
  releaseIds: number[]
  baseUrls: MarkdownBaseUrls
  /** What is being summarized, e.g. "these 3 releases". */
  subject: string
}

/** "Summarize with Claude" for one or more releases. Render with a ``key`` per selection. */
export function SummaryPanel({ releaseIds, baseUrls, subject }: SummaryPanelProps) {
  const config = useSummaryConfig()
  const summarize = useSummarize()
  if (!config.data?.enabled) return null

  if (summarize.data) {
    return (
      <Card size="sm" className="mb-6 bg-primary/5 ring-primary/20">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <SparklesIcon className="size-4 text-primary" aria-hidden />
            Summary
          </CardTitle>
          <CardDescription>Generated by {summarize.data.model}. It can make mistakes.</CardDescription>
        </CardHeader>
        <CardContent>
          <Suspense fallback={<Skeleton className="h-16 w-full" />}>
            <Markdown content={summarize.data.content} baseUrls={baseUrls} />
          </Suspense>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="mb-6 flex flex-col gap-3">
      {summarize.isError && (
        <Alert variant="destructive">
          <AlertTriangleIcon />
          <AlertTitle>Couldn't create a summary</AlertTitle>
          <AlertDescription>{summarize.error.message}</AlertDescription>
        </Alert>
      )}
      <Button
        variant="outline"
        size="sm"
        className="self-start"
        disabled={summarize.isPending}
        onClick={() => summarize.mutate(releaseIds)}
      >
        {summarize.isPending ? (
          <Spinner data-icon="inline-start" />
        ) : (
          <SparklesIcon data-icon="inline-start" />
        )}
        {summarize.isPending ? "Summarizing…" : `Summarize ${subject}`}
      </Button>
    </div>
  )
}
